#devices configuration, three names are predefined for different purposes
#io_relays1: control physical switches
#alarm1: produce bee noise when error occur
#current_sensor1: detect if the power is cut off
devices:
  - type: alarm
    name: "alarm1"
    unit: 1

  - type: relays
    name: "io_relays1"
    unit: 2
    small_port: false

  - type: current_sensor
    name: "current_sensor1"
    unit: 3


#devices to be read and store results in the share variable
devices_read:
  - io_relays1
  - current_sensor1
